#!/bin/bash
set -x
set -e

if [ -z "${SNAP_API_KEY}" ]; then
  echo "Variável de ambiente SNAP_API_KEY não informada!"
  exit -1
fi

if [ -z "${SNAP_PIPELINE_COUNTER}" ]; then
  echo "Variável de ambiente SNAP_PIPELINE_COUNTER não informada!"
  exit -1
fi

for i in "$@"
do
  pushd "${i}" > /dev/null

  if [ "${i}" == 'portal-de-servicos' ] || [ "${i}" == 'editor-de-servicos' ]; then
    docker build --no-cache=true --build-arg=SNAP_API_KEY="${SNAP_API_KEY}" --build-arg=SNAP_PIPELINE_COUNTER="${SNAP_PIPELINE_COUNTER}" -t="servicosgovbr/${i}" .
    docker push "servicosgovbr/${i}"
    docker tag "servicosgovbr/${i}" "servicosgovbr/${i}:${SNAP_PIPELINE_COUNTER}"
    docker push "servicosgovbr/${i}:${SNAP_PIPELINE_COUNTER}"
  else
    docker build --no-cache=true -t="servicosgovbr/${i}" .
    docker push "servicosgovbr/${i}"
  fi

  # Remove imagens que não vão mais ser usadas
  docker rmi -f $(docker images -a -q && true
  # Remove dependencias que não foram removidas no comando anterior
  docker rmi -f $(docker images -a -q && true

  popd > /dev/null
done

