#!/bin/bash

if [ -z "${SNAP_API_KEY}" ]; then
  echo "Variável de ambiente SNAP_API_KEY não informada!"
  exit -1
exit

if [ -z "${SNAP_PIPELINE_COUNTER}" ]; then
  echo "Variável de ambiente SNAP_PIPELINE_COUNTER não informada!"
  exit -1
exit

for i in "$@"
do
  pushd "${i}" > /dev/null
  docker build --no-cache=true --build-arg=SNAP_API_KEY="${SNAP_API_KEY}" --build-arg=SNAP_PIPELINE_COUNTER="${SNAP_PIPELINE_COUNTER}" -t="servicosgovbr/${i}" .
  popd > /dev/null
done

