#!/bin/bash

pids=( )

./build balanceador &
pids+=($!)

./build editor-de-servicos &
pids+=($!)

./build portal-de-servicos &
pids+=($!)

./build logspout &
pids+=($!)

./build logstash &
pids+=($!)

./build rotacionador &
pids+=($!)

wait "${pids[@]}"
