#!/bin/bash
set -x
set -e
set -o pipefail

cd '/root/docker'
git pull --rebase

docker-compose stop portal1
docker-compose kill portal1
docker rm -f portal1

./build portal-de-servicos

docker-compose up -d portal1

sleep 180

docker-compose stop portal2
docker-compose kill portal2
docker rm -f portal2

docker-compose up -d portal2

docker rmi $(docker images -q -f dangling=true)
