#!/bin/bash
set -x
set -e
set -o pipefail

if [ `whoami` == 'root' ]; then
  cd '/root/docker'
  git pull --rebase
fi


docker-compose stop
docker-compose kill

./build portal-de-servicos

docker-compose up -d

set +x

TIMEOUT=1000
while [ "$TIMEOUT" != "0" ] && ! docker exec portal1 curl -s "http://localhost:8080/info"; do
  TIMEOUT=$(expr "$TIMEOUT" - "1")
  sleep 1
done

TIMEOUT=1000
while [ "$TIMEOUT" != "0" ] && ! docker exec portal2 curl -s "http://localhost:8080/info"; do
  TIMEOUT=$(expr "$TIMEOUT" - "1")
  sleep 1
done

set -x
