#!/bin/bash
set -x
set -e
set -o pipefail

function update() {
  docker-compose stop
  docker-compose rm -f $1
  docker-compose up -d

  TIMEOUT=1000

  set +x
  while [ "$TIMEOUT" != "0" ] && ! docker exec $1 curl -s "http://localhost:8080/info"; do
    TIMEOUT=$(expr "$TIMEOUT" - "1")
    sleep 1
  done
  set -x
}

if [ `whoami` == 'root' ]; then
  cd '/root/docker'
  git pull --rebase
fi

./build portal-de-servicos
update portal1
update portal2
